In [1]:
import numpy as np

In [5]:
# Q.1 Create a null vector of size 10 but the fifth value which is 1.
bro = np.zeros(10,dtype = int)
bro[4] = 1
print(bro)

[0 0 0 0 1 0 0 0 0 0]


In [6]:
# Q.2 Create a vector with values ranging from 10 to 49.
bro = np.arange(10,49)
print(bro)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [7]:
# Q.3 Create a 3x3 matrix with values ranging from 0 to 8.
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Q.4 Find indices of non-zero elements from [1,2,0,0,4,0]
bro = np.nonzero([1,2,0,0,4,0])
print(bro)

(array([0, 1, 4], dtype=int64),)


In [ ]:
# Q.5 Create a 10x10 array with random values and find the minimum and maximum values.
arr = np.random.randint(100,size =(10,10))
print(arr)
print(np.min(arr))
print(np.max(arr))